version: '3.8'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v20.2.5
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    hostname: cockroachdb
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data

  app:
    build: .
    depends_on:
      - cockroachdb
    environment:
      - DB_HOST=cockroachdb
      - DB_PORT=26257
      - DB_USER=root
      - DB_NAME=test_db
      - SSL_MODE=disable

volumes:
  cockroachdb_data:
